name = "client-worker"
main = "index.js"
compatibility_date = "2024-03-04"

[[durable_objects.bindings]]
name = "MY_AGENT"
class_name = "MyAgent"

[[migrations]]
tag = "v1"
new_classes = [ "MyAgent" ]

[vars]
MCP_SERVER_URL = "https://server-worker.raranj.workers.dev"
WORKERS_AI_API_TOKEN = "jIkXYHw1sNPJiETxsjuzylAmHeD7xQrVzzcDfla0"

[observability]
enabled = false

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true