name = "client-worker"
main = "index.js"
compatibility_date = "2024-03-04"

[[durable_objects.bindings]]
name = "MyAgent"
class_name = "MyAgent"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyAgent"]

[vars]
MCP_SERVER_URL = "https://server-worker.raranj.workers.dev"
WORKERS_AI_API_TOKEN = "jIkXYHw1sNPJiETxsjuzylAmHeD7xQrVzzcDfla0"