name = "client-worker"
main = "index.js"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "MY_AGENT"
class_name = "MyAgent"

[[migrations]]
tag = "v1"
new_classes = [ "MyAgent" ]

[vars]
MCP_SERVER_URL = "https://server-worker.raranj.workers.dev"

[observability]
enabled = false

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[ai]
binding = "AI"