name = "cf-ai-agent"
compatibility_date = "2024-03-04"
pages_build_output_dir = "."

compatibility_flags = ["durable_object_fetcher_requires_proxy"]

[[d1_databases]]
binding = "devices_db"
database_name = "devices_db"
database_id = "892e0fbf-65f1-4701-b16f-6d9194a32400"