name = "cf-ai-agent"
compatibility_date = "2024-03-04"
pages_build_output_dir = "."

# This binding tells your Pages application how to find the client-worker
[[services]]
binding = "CLIENT_WORKER"
service = "client-worker"