name = "my-agent-worker"
main = "src/index.js"
compatibility_date = "2025-10-08"

[durable_objects]
bindings = [
  { name = "MY_AGENT", class_name = "MyAgent" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyAgent"]

